spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/info?characterEncoding=utf8&useSSL=false
    username: root
    password: 1234567890


pass:
  salt: 123456