spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/info?characterEncoding=utf8&useSSL=false
    username: root
    password: 1234567890
  data:
    mongodb:
      uri: mongodb://infoadmin:root@localhost:27017/info
  servlet:
    multipart:
      max-request-size: 10Mb
      max-file-size: 2Mb





# mybatis 配置
mybatis:
  check-config-location: false
  type-aliases-package: org.ylgzs.info.pojo
  mapper-locations: classpath:mappers/*.xml


# pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql




pass:
  salt: 123456

