spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-request-size: 10Mb
      max-file-size: 2Mb



# mybatis 配置
mybatis:
  check-config-location: false
  type-aliases-package: org.ylgzs.info.pojo
  mapper-locations: classpath:mappers/*.xml


# pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql


# jwt
jwt:
  header: Authorization
  secretKey: ylgzs_info
  expiration: 604800
  tokenHead: "Bearer "